"""add user profile and verification fields

Revision ID: dbeab2ee3ece
Revises: b2c3d4e5f6a7
Create Date: 2026-05-02 12:05:57.136342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbeab2ee3ece'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('deliveries_order_id_key'), 'deliveries', type_='unique')
    op.drop_constraint(op.f('delivery_verifications_order_id_key'), 'delivery_verifications', type_='unique')
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('is_profile_complete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_verified', new_column_name='is_email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_email_verified', new_column_name='is_verified')
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_profile_complete')
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    op.create_unique_constraint(op.f('delivery_verifications_order_id_key'), 'delivery_verifications', ['order_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('deliveries_order_id_key'), 'deliveries', ['order_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
